server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/identity_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 30cE2KCuTKlzWu5bGPGb3CNNZOINTGQAdfXECdHzAoe0SMVgyAFK55j+/rFOigS0
  valid-duration: 20 # Thời gian hết hạn 1 token (thường là 1h: 3600)
  refreshable-duration: 120 # Thời gian hết hạn refresh (thường là 100h: 360000)
